# Generated by Django 5.2.4 on 2025-07-10 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_adquiere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adquiere',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adquiere', to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='adquiere',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_adquiridos', to=settings.AUTH_USER_MODEL),
        ),
    ]
