# Generated by Django 5.2.4 on 2025-07-09 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programaAcademico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_academico', models.ForeignKey(db_column='idProgramaAcademico', on_delete=django.db.models.deletion.CASCADE, to='programaAcademico.programaacademico')),
                ('usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Registra',
                'unique_together': {('usuario', 'programa_academico')},
            },
        ),
    ]
