# Generated by Django 5.2.4 on 2025-07-09 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
        ("programaAcademico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstaDe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        db_column="idCategoria",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categoria.categoria",
                    ),
                ),
                (
                    "programa_academico",
                    models.ForeignKey(
                        db_column="idProgramaAcademico",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programaAcademico.programaacademico",
                    ),
                ),
            ],
            options={
                "db_table": "ConstaDe",
                "unique_together": {("categoria", "programa_academico")},
            },
        ),
    ]
