# Generated by Django 5.2.4 on 2025-07-10 04:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0002_adquiere"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reseña",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valorCalificacion",
                    models.SmallIntegerField(
                        db_column="valorCalificacion",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True, db_column="fecha")),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        db_column="idCurso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reseñas",
                        to="cursos.curso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="idUsuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reseñas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reseña",
                "verbose_name_plural": "reseñas",
                "db_table": "Reseña",
                "unique_together": {("usuario", "curso")},
            },
        ),
    ]
