# Generated by Django 5.2.4 on 2025-07-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreCategoria", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "Categoria",
            },
        ),
    ]
